name: CI

on: [push]

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'npm'
      - name: Install dependencies
        run: npm install
      - name: Install @rollup/rollup-linux-x64-gnu
        run: npm install @rollup/rollup-linux-x64-gnu
      - name: Run tests
        run: npm test
